package us.kbase.test13;

import us.kbase.common.service.ServerException;
import us.kbase.test13.serversideerrors.ServerSideErrorsClient;

import junit.framework.Assert;

public class Test13 {
	
	public Test13(ServerSideErrorsClient client) throws Exception {
	    String val1 = "Server side error";
        try {
            String ret = client.throwErrorOnServerSide(val1);
            Assert.fail("Method shouldn't work because there is an exception on server side");
        } catch (ServerException ex) {
            Assert.assertTrue(ex.getMessage(), ex.getMessage().contains(val1));
        }
	}
}